-- SQL statements which are executed at application startup if hibernate.hbm2ddl.auto is 'create' or 'create-drop'
-- Inserisce gli anni su cui si calcano i dati di bilancio
INSERT INTO `mics`.`anno_bilancio` (`anno`) VALUES (2007);
INSERT INTO `mics`.`anno_bilancio` (`anno`) VALUES (2008);
INSERT INTO `mics`.`anno_bilancio` (`anno`) VALUES (2009);
INSERT INTO `mics`.`anno_bilancio` (`anno`) VALUES (2010);
INSERT INTO `mics`.`anno_bilancio` (`anno`) VALUES (2011);
-- Inserisce i trimestri su cui si effettua la simulaizone
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (1, 'Primo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (2, 'Secondo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (3, 'Terzo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (4, 'Quarto');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (5, 'Quinto');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (6, 'Sesto');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (7, 'Settimo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (8, 'Ottavo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (9, 'Nono');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (10, 'Decimo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (11, 'Undicesimo');
INSERT INTO `mics`.`trimestre_simulazione` (`trimestre`, `nome_trimestre`) VALUES (12, 'Dodicesimo');
-- Glossario 
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('roe', 'Esprime in massima sintesi i risultati economici dell’azienda. È un indice di percentuale per il quale il reddito netto prodotto viene rapportato al capitale netto o capitale proprio, ossia alla condizione di produzione di diretta pertinenza. Per poter dire se un dato valore di ROE è buono o cattivo bisogna metterlo a confronto con il rendimento di investimenti alternativi (BOT, CCT, depositi bancari, ecc.), cioè valutare il costo opportunità dell’investimento nell’azienda in questione.', 'ROE (Return On Common Equity)','%');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('debitiBancheSuFatturato', 'Rapporto tra debiti bancari (a breve e a lungo) e fatturato. Indica in valori assoluti quanto pesa il debito bancario (a breve e a medio-lungo termine) sul fatturato dell’azienda nell’anno in considerazione.', 'Debiti v/banche su fatturato','%');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('ebitda', 'Rappresenta l’utile prima degli interessi passivi, imposte e ammortamenti su beni materiali e immateriali). L’EBITDA, risulta utile per comparare i risultati di diverse aziende che operano in uno stesso settore attraverso i multipli comparati (utili in fase di decisione del prezzo in un’offerta pubblica iniziale). È spesso utilizzato poiché è molto simile al valore dei flussi di cassa prodotti da una azienda, e quindi fornisce l’indicazione più significativa al fine di valutarne il valore. Può essere inoltre utilizzato per calcolare il risultato operativo di un’azienda, partendo dall’utile lordo, togliendo le imposte, gli ammortamenti, i deprezzamenti e gli interessi dell’azienda. Se i costi saranno maggiori dei ricavi, si avrà una perdita, rispettivamente se figureranno dei ricavi maggiori dei costi, si avrà un utile. L’EBITDA è un dato più importante dell’utile per gli analisti finanziari perché permette di vedere chiaramente se l’azienda è in grado di generare ricchezza tramite la gestione operativa, escludendo quindi le manovre fatte dagli amministratori dell’azienda (ammortamenti e accantonamenti, e gestione finanziaria) che non sempre danno una visione corretta dell’andamento aziendale. \nEbitda inferiore al 10% del fatturato: indicano un prodotto povero, azienda indebitata. Ebitda tra il 10% e il 15%: discreto risultato; Ebitda tra il 15% ed il 20%: buon risultato; Ebitda superiori al 20%: aziende che eccellono nel loro settore per tecnologia, marketing, servizio o per altri elementi particolarmente distintivi. \nTuttavia questo schema diverge da settore a settore, per esempio: a) le imprese di distribuzione all’ingrosso mostrano invece valori dell’indice solitamente inferiori nell’ordine di 7-10 punti percentuali rispetto a quanto detto per le aziende industriali; b) le imprese di distribuzione al dettaglio hanno solitamente un EBITDA inferiore di altri 1-2 punti percentuali rispetto alla distribuzione all’ingrosso; c) per le imprese di servizi i valori medi dell’indice sono aumentati di 5 punti percentuali rispetto alle aziende industriali.', 'EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization)','€');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('roi', 'Indica la redditività e l’efficienza economica della gestione caratteristica a prescindere dalle fonti utilizzate: esprime, cioè, quanto rende il capitale investito in quell’azienda. In particolare si rileva come nella determinazione della redditività aziendale rivesta un ruolo fondamentale la redditività della gestione caratteristica sintetizzata dall’indice di redditività del capitale investito - ROI, calcolato rapportando il Reddito operativo al Capitale investito. E’ a livello di gestione caratteristica che si pongono le basi per una redditività aziendale soddisfacente e duratura. Il ROI sintetizza l’efficienza con la quale si è utilizzato il capitale impiegato nell’attività tipica dell’impresa, indipendentemente da come la stessa è stata finanziata. Il reddito operativo, quale numerato del rapporto, è infatti il risultato derivante dal contrapporsi di ricavi e costi legati alla gestione caratteristica dell’impresa; esso viene perciò influenzato solo dalle politiche intraprese per il reperimento e l’impiego dei fattori di produzione e per la commercializzazione dei prodotti.', 'ROI (Return On Investment)','%');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('costoLavoroProCapite', 'Costo del lavoro pro capite al lordo delle ritenute fiscali e dei contributi sociali.', 'Costo del lavoro','€');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('quotaAmmortamentoBeniMateriali', 'Insieme di tutti i fattori produttivi ad utilità pluriennale fisicamente tangibili (ad es. fabbricati, macchinari, impianti, automezzi, attrezzature industriali e commerciali, computer, mobili d’ufficio ecc.).', 'Ammortamento beni materiali','€');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('costiProdGodimentoBeniTerzi', 'L’impresa, nello svolgere la propria attività, si serve a vario titolo di beni che non sono di sua proprietà per i quali è tenuta a pagare un compenso. Per questa ragione nel piano dei conti di ogni impresa sono presenti alcuni conti che servono a rilevare i costi sostenuti dall’impresa per il Godimento dei beni di terzi.\nL’impresa, nello svolgere la propria attività, si serve a vario titolo di beni che non sono di sua proprietà per i quali è tenuta a pagare un compenso. Per questa ragione nel piano dei conti di ogni impresa sono presenti alcuni conti che servono a rilevare i costi sostenuti dall’impresa per il Godimento dei beni di terzi.\nL’impresa, nello svolgere la propria attività, si serve a vario titolo di beni che non sono di sua proprietà per i quali è tenuta a pagare un compenso. Per questa ragione nel piano dei conti di ogni impresa sono presenti alcuni conti che servono a rilevare i costi sostenuti dall’impresa per il Godimento dei beni di terzi.', 'Godimento beni di terzi','€');
INSERT INTO `mics`.`glossario` (`name`, `definizione`, `vocabolo`,`unitaDiMisura`) VALUES ('quotaAmmortamentoBeniImmateriali', 'L’ammortamento costituisce un processo di ripartizione del costo delle immobilizzazioni immateriali in funzione del periodo in cui l’impresa ne trae beneficio, e solo in conseguenza di ciò, esso contribuisce – in un sistema contabile basato sul costo – alla valutazione delle immobilizzazioni. Le immobilizzazioni immateriali sono caratterizzate dalla mancanza di tangibilità: per questo vengono definite “immateriali”. Le immobilizzazioni immateriali compren-dono: a) i costi plu-riennali che non si concre-tizzano nell’acquisizione o produzione interna di beni o diritti (costi di impianto e di ampliamento, costi di ricerca e di sviluppo e di pubblicità, ecc.), - b) l’avviamento (che però in questa sede escludiamo), - c) i beni immateriali (diritti di brevetto industriale e diritti di utilizzazione delle opere dell’ingegno, concessioni, licenze, nonché i diritti simili), - d) i costi interni ed esterni sostenuti per beni immateriali in corso di produzione o di acquisto, compresi i relativi acconti. ', 'Ammortamento beni immateriali','€');

